name: gms_services
description: Flutter плагин для работы с Google Mobile Services.
version: 0.0.1

environment:
  sdk: ^3.10.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^4.0.0
  firebase_remote_config: ^6.0.0
  firebase_messaging: ^16.0.0
  firebase_analytics: ^12.0.0
  firebase_crashlytics: ^5.0.0

  logger: ^2.6.2

  hive_ce: ^2.15.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
