name: gms_services
description: Flutter плагин для работы с Google Mobile Services.
version: 0.0.1

environment:
  sdk: ^3.10.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^4.2.1
  firebase_remote_config: ^6.1.2
  firebase_messaging: ^16.0.4
  firebase_analytics: ^12.0.4
  firebase_crashlytics: ^5.0.5

  logger: ^2.6.2

  hive_ce: ^2.15.1
  path_provider: ^2.1.5

  advertising_id: ^2.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
